const PROJECTS = [
  {
    title: "CertifyCraft: Certificate Generation Tool",
    skills: "HTML, CSS, Bootstrap, JavaScript, Django, Python",
    description: "As a committee member, I contributed to a web app that significantly accelerated certificate creation, enhanced user interface, and streamlined post-event processes",
    link: "https://github.com/rajfirke/Certificate_Generator",
    category: "SD",
    image: "./assets/images/projects/img6.png",
  },
  {
    title: "SentimentSeek: Twitter Sentiment Analysis",
    skills: "Python, Scrapping, Sentiment Analysis, NLP",
    description: "This project showcases how to utilize the Nitter library to scrape tweets from Twitter, followed by sentiment analysis on the tweets using NLTK library's VADER sentiment analyzer.",
    link: "https://github.com/rajfirke/Twitter-Scrapping-and-Sentiment-Analysis",
    category: "ML",
    image: "./assets/images/projects/img1.png",
  },
  {
    title: "PDF Precisifier: PDF Summarization",
    skills: "Python, LLM, Hugging-face, NLP",
    description: "This project aims to expedite the summarization of lengthy PDF documents, such as research papers or chapters, by providing an abstractive summary, thereby saving valuable time.",
    link: "https://github.com/rajfirke/PDF-Summary",
    category: "ML",
    image: "./assets/images/projects/img2.png",
  },
  {
    title: "NewsNest: Article Scraping & Classification",
    skills: "Python, Web Scrapping, Classification",
    description: "This application conducts web scraping on the Economics Times website to gather news articles, subsequently employing text classification techniques to categorize them into distinct sections, using machine learning-based classification.",
    link: "https://github.com/rajfirke/News-article-scraping-and-classification",
    category: "ML",
    image: "./assets/images/projects/img3.png",
  },
  {
    title: "Smart India Hackathon 2022",
    skills: "HTML, CSS, Python, NLP, MySQL, Flask, LLM",
    description: "Participated in the Smart India Hackathon, leveraging NLP to align college syllabi with 33 ACM knowledge areas in Computer Engineering, while also devising a scoring system for thorough assessment using Semantic Similarity",
    link: "https://github.com/rajfirke/Smart-India-Hackathon-2022",
    category: "SD",
    image: "./assets/images/projects/img4.png",
  },
  {
    title: "HomeWise: House Price Prediction",
    skills: "Python, Colab, Machine Learning",
    description: "I developed a project to forecast house prices in Pune by meticulously analyzing relevant features, ensuring only pertinent ones were selected, and subsequently employing machine learning models for accurate price predictions.",
    link: "https://github.com/rajfirke/House-price-prediction",
    category: "ML",
    image: "./assets/images/projects/img5.png",
  },
];
